---
  server:
    port: 8080

  spring:
    datasource:
      url: jdbc:postgresql://localhost/SpringTesting
      username: postgres
      password: 99331133

      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
